### ISSUE TITLE
Messages communs à modifier

### ISSUE THREAD

**Issue by noftaly** [horizon-efrei/HorizonBot#11]
Pouvoir créer un message commun auquel toutes les personnes avec une certaines permission peuvent apporter des modifications

**Comment by gtedavid** [comment]
Pourrait être fait par webhooks, mais devrait être contraint pour le push et maj à être réservé pour certains rôles uniquement

**Comment by gtedavid** [comment]
@noftaly Go pour des webhooks, mais je sais pas si c'est possible de le faire sur une branche différente par rapport aux annonces, car c'est pas des annonces, mais des msg pushed une fois et modifiables via le webhook......

**Comment by noftaly** [comment]
Je close l'issue car on en a jamais eu besoin, et pour tout ce qui est annonce, règles, guide etc on a déjà les webhooks
