### ISSUE TITLE
Programmer des réunions

### ISSUE THREAD

**Issue by noftaly** [horizon-efrei/HorizonBot#16]
Commande de gestion de réunion
- Programmation à l'avance
- Rappel en proposant un rôle que les participants auront eu a l'avance en s'inscrivant
- Définir quel rôle est censé être présent
- Pouvoir voir les gens avec ce rôle qui ne sont pas venus

**Comment by gtedavid** [comment]
-> Pas prio

Apollo utilisable 
-> A voir pour éviter +1Bot + à devoir configurer pour certains rôle uniquement

**Comment by gtedavid** [comment]
-> /issue setstatus sleep inf

**Comment by noftaly** [comment]
On peut maintenant utiliser les évènements Discord, qui servent exactement à cela
