### ISSUE TITLE
Horaires de train/bus/métro RATP au départ des gares près de l'école

### ISSUE THREAD

**Issue by noftaly** [horizon-efrei/HorizonBot#20]
Commande pour voir les horaires des prochains bus, métros etc au départ des gares prêt de l'école.

**Comment by Kethash** [comment]
Api toute préparée sur https://github.com/pgrimaud/horaires-ratp-api

**Comment by gtedavid** [comment]
petite faute dans le titre 

> ... prêt de l'école

-> près de
bonne idée par contre

**Comment by noftaly** [comment]
L'application Bonjour RATP est très bien faite et permet de mettre des arrêts en Favori.
Jsp si Ef'Réussite et HorizonBot sont vraiment le meilleur endroit pour supporter ca.
