### ISSUE TITLE
Newsletter / Résumeur d'annonces (MP)

### ISSUE THREAD

**Issue by iv-stpn** [horizon-efrei/HorizonBot#21]
Une forme de newsletter qui enverrait des résumés condensés d'annonces ou des informations détaillées par MP (via le bot en lui-même)

Un utilisateur peut s'abonner à la newsletter via une réaction sur un message "important"

En communiquant en MP avec le bot, l'utilisateur aura aussi un rappel sur le fait que des commandes utilitaires sont disponibles, et éventuellement pourra choisir d'avoir des annonces supplémentaires relatives au développement du projet, à des MaJ, etc.

[La tâche principale ici est de composer les textes]

**Comment by gtedavid** [comment]
Ça serait 1 rôle ou plusieurs dans l'idéal ?

**Comment by noftaly** [comment]
> Ça serait 1 rôle ou plusieurs dans l'idéal ?

Cette feature date de l'époque où Ef'Réussite relayait toutes les informations (relatives aux assos, a l'efrei, au discord etc). Aujourd'hui on a beaucoup moins d'informations, que des choses importantes, déjà condensées, et "rares" (pas plus d'une toutes les deux semaines en général).
Je ne pense pas que cette commande fasse encore sens, alors je ferme 😄
