### ISSUE TITLE
Message de validation RGPD (MP)

### ISSUE THREAD

**Issue by iv-stpn** [horizon-efrei/HorizonBot#24]
Pour qu'une personne puisse officiellement rejoindre le serveur, elle doit d'abord accepter la charte RGPD

La charte RGPD détaille les données de l'utilisateur que nous stockons, leur visibilité, leur rétention, etc.

Après avoir pris le rôle "Efrei" sur le message d'accueil du serveur, le bot envoie une confirmation RGPD à l'utilisateur; l'utilisateur accepte cette charte en réagissant ☑️

Une fois la charte acceptée, l'utilisateur obtient le rôle Efrei

**Comment by gtedavid** [comment]
On peut l'inclure dans une des règles à valider via le Welcome Screen 
A moins que vous vouliez avoir une interface complètement consacrée au sujet....

**Comment by noftaly** [comment]
Je suis d'accord avec David, on a le Welcome Screen, ca serait logique de l'y mettre !
Je close
