### ISSUE TITLE
Commande pour obtenir le raccourci Moodle d'un document

### ISSUE THREAD

**Issue by iv-stpn** [horizon-efrei/HorizonBot#28]
!document

=> renvoie la liste des noms valides de documents (~15 carac max chaque pour l'ergonomie)

!document <nom_du_document>

=> renvoie un raccourci myEfrei/Horizon vers le document

Certains documents pourraient être résumés par un embed (qu'il faudra sûrement créer manuellement), par exemple les salles pour les examens

[La difficulté principale de ce bot est de regrouper tous les documents importants pour les étudiants, et d'assurer la rotation à chaque semestre]

**Comment by noftaly** [comment]
Est ce que moodle a une API qui permet ca, et si oui elle requiert un un compte & une authentication. Est ce que l'école nous créera ce compte et nous donnera permission de récup les docs moodle avec un bot ? pas sûr

**Comment by iv-stpn** [comment]
Il s'agit juste d'un dictionnaire qui map les noms des documents à leurs liens moodle, c'est fait manuellement comme j'ai précisé à la fin

La difficulté est triviale, j'avais oublié de le noter

**Comment by iv-stpn** [comment]
Cela dit on pourrait rajouter la possibilité d'avoir des abbréviations, des ID ou une tolérance sur les fautes d'orthographe potentiellement, ce qui augmenterait un peu la difficulté

**Comment by noftaly** [comment]
> Il s'agit juste d'un dictionnaire qui map les noms des documents à leurs liens moodle, c'est fait manuellement comme j'ai précisé à la fin

Ah ca renvoie juste les liens moodle ? Mais il faut mettre ca a jour manuellement du coup ?

**Comment by iv-stpn** [comment]
Oui, comme j'ai écrit a la fin
Peut-être que ça n'était pas expliqué assez clairement, my bad

**Comment by noftaly** [comment]
> La difficulté principale de ce bot est de regrouper tous les documents importants pour les étudiants, et d'assurer la rotation à chaque semestre

Oui je pensais que tu coup c'était au bot de regrouper les documents et d'assurer la rotation 😅 

Du coup pour ca y'a 2 trucs:
- Soit on utilise la commande de tag qui existe déjà, par exemple on créé un tag "moodle" avec comme alias "doc" et "docs", puis dans la commande on met la liste des documents récurrents, et ensuite on peut juste faire `!moodle` ou `!doc` etc et ca nous donne la liste. On peut aussi utiliser cette commande mais en créant un tag par doc ou par groupe de docs
- On créé une commande spéciale pour ca comme tu proposes, mais du coup oui comme tout est manuel, c'est assez simple :)
