### ISSUE TITLE
Liste des personnes avec une intersection de rôles

### ISSUE THREAD

**Issue by iv-stpn** [horizon-efrei/HorizonBot#29]
!inter-list <rôle1> <rôle2> <rôle3>

=> renvoie une liste à puce des personnes avec le rôle; toutes les personnes susceptibles d'être pingés sont remplacées par le pseudo en plaintext (éventuellement avec un paramètre qui peut permettre de pinger optionnellement --ping)

**Comment by Kethash** [comment]
Hey ! Pourrais-tu expliquer ce qu'est une intersection de rôles ? Cette commande permettrait de savoir quelles personnes ont ces rôles à la fois ?

**Comment by noftaly** [comment]
> Hey ! Pourrais-tu expliquer ce qu'est une intersection de rôles ? Cette commande permettrait de savoir quelles personnes ont ces rôles à la fois ?

Hello, oui c'est exactement ça :) Donc ce que Ivan voudrait c'est que ca retourne la liste des utilisateurs (`user.tag`, qui affichera `pseudo#discriminant`, genre `noftaly#0359`), ou les mentionne si on met `--ping`.
Pour regarder comme ajouter un flag comme ca, tu peux regarder la commande "Admin/pingRoleIntersection" où on a ajouté un flag `--keep`/`-k`, et on check son existence avec la variable `isPersistent` :)
GL

<details>
<summary>(si tu veux prendre cette issue, hésite pas a te l'assigner et a la mettre dans la colonne "In Progress" 😄 )</summary>

<img width="539" alt="image" src="https://user-images.githubusercontent.com/34779161/133939131-9bbaf6e4-f7fd-4c20-a710-31043529c904.png">
</details>

**Comment by gtedavid** [comment]
cette commande est un doublon je crois, vu qu'on a dump maintenant 
A part si on le garde pour le cas précis des rôles intersections.....

**Comment by noftaly** [comment]
Tu as raison la demande originelle déjà résolue avec le !dump ! Merci? Je close
