### ISSUE TITLE
Feature pour délégués: TODO-list de devoirs

### ISSUE THREAD

**Issue by iv-stpn** [horizon-efrei/HorizonBot#31]
Ensemble de commandes pour gérer de façon semi-automatique une liste de devoirs à faire pour les délégués dans les classes

Commandes à prévoir: !todo create <liste des matières>, !todo add <matière> <intitulé> <date due>, !todo remove <matière/intitulé>, !todo edit <intitulé>, !todo archive 

Exemple de layout (devoirs à faire):

--- DEVOIRS A FAIRE (S8) ----

**Natural Language Processing (NLP): (projet terminé  ❌  DE Passé ❌)**

- Amazon TP Analysis (01/02)

- TP1: Analysis of Presidential Speeches (05/02)

- Envoyer un HTML/PDF du Notebook (avant le 06/02)

Exemple de layout archive:

--- DEVOIRS FAITS (S7) ----

**Big Data Frameworks: (projet terminé :ballot_box_with_check: DE Passé :ballot_box_with_check: )**

- TP4 Lab1 avec Markdown (15 Oct. 23:59 sur Moodle)

- TP4 Lab2 (Yarn/JAVA) (12 Nov. 23:59 sur Moodle)

- TP5 (Hive) (15 Nov. 23:59 sur Moodle)

- TP6 (HBase) (23 Nov, pas de rendu)

**Comment by gtedavid** [comment]
Trello & Click-Up sont de bonnes solutions
