### ISSUE TITLE
Utiliser les boutons, context-menus, selects-menus

### ISSUE THREAD

**Issue by noftaly** [horizon-efrei/HorizonBot#33]
Il faudrait mettre à jour le bot pour utiliser les nouvelles "Interactions" discord:
- Les boutons
- Les context-menus (options au clique-droit)
- Les selects-menus (dropdowns)

Example de commande ou ça pourrait être ajouter:
- Reaction Role
- Setup (dropdown pour set un channel)
- Tags (dropdown dans la liste)
- Help (dropdown dans la liste)
- Statistics (boutons avec divers liens)
- ~~Eclass~~ *(fait)*

**Comment by gtedavid** [comment]
Waiting for : slash command librairies
