### ISSUE TITLE
Ajouter des "classes partielles"

### ISSUE THREAD

**Issue by noftaly** [horizon-efrei/HorizonBot#35]
Pouvoir créer une classe mais avec des champs manquants (uniquement `sujet`, `date`, `durée`, `professor`, et `isRecorded`).

Le cours sera marqué comme "Incomplet", ne sera pas annoncé et ne pourra pas être lancé.
On peut ensuite définir les champs manquants via le edit (ou commande spéciale `continue` qui affiche l'embed comme `create` ??), et quand tous les champs requis ont été ajoutés, commande pour valider le cours dans son état actuel (`finalize` ?) (= l'annoncer et le marquer en "prévu" pour qu'il soit lançable).

**Comment by gtedavid** [comment]
-> Utilité peu apparente pour le moment 

=> /issue setstate sleep Infinite
