### ISSUE TITLE
Améliorer la commande "Subject"

### ISSUE THREAD

**Issue by noftaly** [horizon-efrei/HorizonBot#36]
Améliorer la commande `Professors/subjects`:
- Ajouter une sous-commande pour modifier une matière (avertir des e-class l'utilisant actuellement)
- Ajouter une sous-commande pour gérer les examens
- Améliorer l'affichage dans la liste
- Ajouter la possibilité de pouvoir set le channel docs et le channel voice

**Comment by gtedavid** [comment]
Note
le voice chat pour le moment n'est que pour la catégorie et non la matière...

**Comment by noftaly** [comment]
Problème résolu : elle a été supprimée
