### ISSUE TITLE
Ajouter une commande pour purge des messages

### ISSUE THREAD

**Issue by noftaly** [horizon-efrei/HorizonBot#44]
Ajouter une commande qui supprime (purge) des messages (max 100, limitation de l'API discord).

Arguments/flags/options (tous facultatifs):
- `<nombre>` : nombre de message à supprimer (entre 1 et 100 inclus) : défaut à 10.
- `<user>` : utilisateur à qui supprimer les messages (attention : utilisateur, pas membre) : défaut à tout le monde
- `--files` : supprimer seulement les messages contenant des pièces jointes
- `--me` : supprimer seulement les messages de l'auteur
- `--bot` : supprimer seulement les messages des bots
- `--human` : supprimer seulement les messages des non-bots
- `--link` : supprimer seulement les messages contenant des liens
- `--invite` : supprimer seulement les messages contenant des invitations discord

**Comment by gtedavid** [comment]
N.B. une des fonctionnalités qui seraient à implémenter pour virer Carl
