### ISSUE TITLE
Plusieurs rôles pour les conditions des Réaction-Rôles

### ISSUE THREAD

**Issue by noftaly** [horizon-efrei/HorizonBot#45]
Ajouter la possibilité de définir plusieurs rôles pour les conditions des réaction role.

BONUS: pouvoir définir si on veut que ce soit un "OU" entre tous les rôles, ou un "ET".

**Comment by gtedavid** [comment]
- au lieu que les rôles par rapport aux inter etc soit uniquement accessible pour les parcours ingé qui est lui bloqué par le rôle efrei uniquement, permettre à ce que les ex-efrei ou les anciens (Alumni) puissent aussi les choisir

https://discord.com/channels/694220883815956580/971738273774968852/972406455128961066

**Comment by gtedavid** [comment]
Bloquer la possibilité à certains rôles de réagir sur des menus réactions https://discord.com/channels/694220883815956580/971738273774968852/985191724638937168

**Comment by gtedavid** [comment]
- permettre aux rôles d'eprof (plusieurs rôles) à réagir sur un menu https://discord.com/channels/694220883815956580/971738273774968852/972945553417707560

**Comment by gtedavid** [comment]
> * au lieu que les rôles parcours ingé etc soient uniquement accessibles pour les parcours ingé dont l'obtention du rôle est lui bloqué par la possession du rôle Efrei uniquement, permettre à ce que les ex-efrei ou les anciens (Alumni) puissent aussi les choisir
> 
> https://discord.com/channels/694220883815956580/971738273774968852/972406455128961066

-  https://discord.com/channels/694220883815956580/971738273774968852/972944248456487003  permettre aux rôles efrei et alumni à prendre des rôles dans ✨-roles-pex 🖥-roles-ingé 🧢-roles-généraux

**Comment by lauragossip** [comment]
Ça dépend de quel menu on parle mais je vois plus trop l’intérêt car souvent à partir du moment où on a un rôle même si le menu change on garde le rôle

**Comment by gtedavid** [comment]
> Ça dépend de quel menu on parle mais je vois plus trop l’intérêt car souvent à partir du moment où on a un rôle même si le menu change on garde le rôle

True

**Comment by noftaly** [comment]
Ça va aussi être rendu obsolète par l'onboarding dès qu'on l'a...

**Comment by gtedavid** [comment]
> Ça va aussi être rendu obsolète par l'onboarding dès qu'on l'a...

Oui et non

L'Onboarding ne permet pas de mettre des conditions de rôles pour le choix
Il rend uniquement obligatoire ou non, s'il y a le droit à plusieurs choix et si la question apparaît parmi celles posées à l'utilisateur à son arrivée sur le discord

**Comment by gtedavid** [comment]
Ça a été mentionné dans DAC, mais je ne sais pas si c'est prévu sur leur Roadmap.....

**Comment by noftaly** [comment]
Avec l'arrivée de l'onboarding nous n'avons plus aucun reaction-role, donc je ne vais pas ajouter de nouvelles features surtout si ca complique encore plus le système
