### ISSUE TITLE
Seuil de participants au cours

### ISSUE THREAD

**Issue by noftaly** [horizon-efrei/HorizonBot#46]
Commande pour ajouter un seuil de participant aux cours.
Par exemple, si on met le seuil à 15 personnes, ~2h avant le cours il va regarde s'il y a au moins 15 personnes inscrites. Si oui, rien ne ce passe, mais si non, le cours est annulé, reporté, ou le prof est notifié.
Ce serait affiché dans l'embed d'annonce de cours

**Comment by gtedavid** [comment]
participant**s**

**Comment by gtedavid** [comment]
**!!! Les cours pour les rattrapages, il y a moins d'étudiants**
ils sont malgré tout maintenu malgré un nombre peu important pour permettre aux étudiant(e)s de poser leur(s) question(s) et permettre de réviser

**Comment by noftaly** [comment]
> **!!! Les cours pour les rattrapages, il y a moins d'étudiants**
> ils sont malgré tout maintenu malgré un nombre peu important pour permettre aux étudiant(e)s de poser leur(s) question(s) et permettre de réviser

oui ce serait configurable par cours, l'eprof choisit ce qu'il veut pour son cours. Et ce serait facultatif
