### ISSUE TITLE
Commande !todo & !done

### ISSUE THREAD

**Issue by iv-stpn** [horizon-efrei/HorizonBot#48]
Les responsables de pôles peuvent donner des tâches à leurs membres en utilisant une commande todo avec la syntaxe suivante :

**!todo <@rôle pôle> <nom_tache> <jj/mm (deadline)> <description> <@personne1> <@personne2> <@personne3...>**

Un rappel sera envoyé automatiquement à la personne pour la tâche la veille de la deadline
=> On peut imaginer une commande **!remind** pour envoyer un rappel aux gens ou une option dans la commande todo pour envoyer un rappel à une date donnée

Une fois qu'un membre a terminé sa tâche, il peut faire la commande **!done <nom_tache>** pour terminer sa tâche. Si plusieurs membres étaient assignés à une même tâche, il faut envoyer un message de confirmation à la personne, demandant si tout le monde a terminé la tâche où si le membre a juste terminé sa partie (auquel cas il faut attendre que tous les membres assignés aient terminé la tâche pour la valider).

Une notification est envoyée dans le bureau une fois qu'une tâche est complétée. Il est possible de faire:

**!todo <@rôle pôle> ls
!done <@rôle pôle> ls**

pour voir la liste des tâches à faire/faites des pôles avec quelques infos comme la deadline, qui est/était assigné, qui a validé sa partie (si plusieurs membres sont assignés à la tâche), etc.

**Comment by noftaly** [comment]
Je close l'issue car on en a jamais eu besoin finalement, et c'est très overkill. Un simple message avec la liste des choses à faire dans le salon du pôle suffit
