### ISSUE TITLE
Bug sur les rappel - accepte un edit vide

### ISSUE THREAD

**Issue by gtedavid** [horizon-efrei/HorizonBot#53]
**Accepte l'édition vide d'un rappel**

https://discord.com/channels/827518251608178728/829765627513405501/932771624158130217
**Pour reproduire**

1. Étape 1
2. Étape 2
3. Étape 3...
(Voir lien au-dessus)
**Comportement attendu**

**Screenshots**

**Comment by noftaly** [comment]
Salut :) merci pour le report, mais ce n'est pas un bug, j'accepte intentionnellement les rappels sans description si tu veux juste te faire ping pour te rappeler quelque chose.
Tu penses que ce n'est pas une bonne idée ?

**Comment by gtedavid** [comment]
Peut-être une confirmation ou un -p argument pour considérer que c'est un ping.....
Un ping sans lui mettre un nom pour te rappeler de qlq ch c'est un peu bizarre 😅

Mais je comprends ce que tu voulais faire

**Comment by gtedavid** [comment]
Rappel vide - Comportement normal et logique
