### ISSUE TITLE
Aucune trace des slash cmds

### ISSUE THREAD

**Issue by gtedavid** [horizon-efrei/HorizonBot#59]
**Aucun traçage de l'exécution des commandes réalisées en slash**

**Pour reproduire**

1. Taper n'importe quelle commande
2. Aucun log dans le bot de msg supprimé (ou de cmd exécutée ?)

**Comportement attendu**

L'affichage de la suppression de message ou de commande

**Screenshots**

**Comment by gtedavid** [comment]
impossible to trace

**Comment by noftaly** [comment]
Les bots ont acces que aux commandes envoyées a ce bot la. C’est le principe des slashs commandes, c’est vraiment juste entre l’user, le serv et le bot ; pas les autres membres. 

C’est pas un message classique ^^ Donc dsl mais je peux rien y faire afaik

**Comment by gtedavid** [comment]
tkt je comprends
c'est dommage qu'on puisse même pas tracer les cmds buit-in
