### ISSUE TITLE
AFK command

### ISSUE THREAD

**Issue by gtedavid** [horizon-efrei/HorizonBot#61]
Level Priority : low

AFK command

Modifie pseudo serveur pour période donnée avant de réinitialiser

Si tag, msg dans le chat du tag en disant la raison afk, prise de connaissance du msg dès que possible

-> permettre de réduire pression à répondre dès tag si occupé(e) par autre chose pour le moment

**Comment by Serquand** [comment]
J'ai pas compris là..
En gros tu fous - AFK à la fin de ton pseudo et tu te bouffes pas de ping ?

**Comment by noftaly** [comment]
Non ce serait comme les mails automatique, quand quelqu'un te ping ou te répond, ca envoie "machin est absent pour le moment, il vous répondra plus tard".
Mais je ne suis pas convaincu de la pertinence, car si t'es absent tu te mets juste en AFK/invisible et les gens verront + personne n'attend de toi une réponse immédiate, ca reste un réseau social, si tu veux répondre dans 2 semaines y'a pas de soucis y'a aucune exigence d'imposée

**Comment by gtedavid** [comment]
> personne n'attend de toi une réponse immédiate

me problem maybe then 😅😢
