### ISSUE TITLE
Possibilité de modifier/corriger le rôle - Édition d'un cours

### ISSUE THREAD

**Issue by gtedavid** [horizon-efrei/HorizonBot#62]
**Impossible de changer le rôle du cours après création**

**Pour reproduire**

1. !ecours edit IDCOURS rôle nom_du_Rôle
2. Bot : Cette propriété est invalide. Choisis parmi "sujet", "date", "heure", "durée", "professeur" et "rôle".

**Comportement attendu**

Le XXX a bien été changé sur `@role` 

**Screenshots**

https://discord.com/channels/694220883815956580/890287976809132092/989712734650236988
Unknown if corrected

**Comment by noftaly** [comment]
Je viens d'y réflechir, mais modifier cette valeur n'a pas de sens car le sel endroit où le rôle est utilisé, c'est dans le ping initial pour avertir les gens du nouveau cours.
Hors si on modifie ce ping, je pourrai faire que ca modifie le message initial, mais ca n'aurait aucun impact car rajouter une mention dans un message modifié ne le mentionne pas.

En gros, ca va juste modifier le message, mais les gens qui ont été ping avec le 1er rôle seront toujours ping, et les gens qui auraient du être ping avec le second rôle ne seront pas ping. = aucun impact, mis a part peut être de la confusion car les gens vont voir le nouveau rôle dans le message, se dire pourquoi ils ont pas été ping alors qu'ils ont le rôle etc.

qu'en penses-tu ?

**Comment by gtedavid** [comment]
le souci que je crois que Elliot parle, c'est le ghost ping.....

Ou alors, ça serait d'avoir une option de suppression du msg (avec excuse du ping pour le rôle `@ blablabla` c'était une erreur, et nouveau msg avec bon ping, mais on pingerait double certain(e)s....

Je vais aussi voir ce que Laura en pense

Pour le moment, on peut diminuer la priorité de celle-ci, le temps qu'on brainstorm ce qui serait le mieux

**Comment by noftaly** [comment]
> Du coup refaire un message en supprimant l'ancien ?

Comme David l'a dit en effet ca ferait des ghost pings voire double-ping pour certains avec les deux rôles...

**Comment by Serquand** [comment]
Oui mais est-ce que le pire serait d'avoir des double ping, ce qui correspond à juste une notification un truc rouge quoi, ou est-ce que c'est que certaines personnes ne soient pas au courant du cours ?

**Comment by lauragossip** [comment]
> Oui mais est-ce que le pire serait d'avoir des doubles ping, ce qui correspond à juste une notification un truc rouge quoi, ou est-ce que c'est que certaines personnes ne soient pas au courant du cours ?

En vrai je pense que le pire c'est le ghost ping, car ils ne voient pas du coup quand il y a un cours qui est programmé et donc ils ne sont pas au courant.

**Comment by lauragossip** [comment]
Mais apres je trouve ça dommage que ça ne tague pas le nouveau rôle quand on le modifie.

**Comment by Serquand** [comment]
> 

What ? Si justement ils voient...

**Comment by noftaly** [comment]
Pour beaucoup, dont moi, un ping est beaucoup plus qu'un petit point rouge.
Déjà c'est une notification sur ton téléphone, parfois sonore, pareil sur ordi ca fait un son, et puis c'est un ping inutile, qui aurait pu être évité.

Mais ca serait qd même mieux de pouvoir modifier le cours et de faire comme david a dit, une phrase d'excuse pour le rôle d'avant, plutôt que de devoir cancel le cours et le recréer

**Comment by lauragossip** [comment]
> What ? Si justement ils voient...
> Ils voient même quand il n'y a pas de cours de prévu pour eux car le cours a été modifié...

Oui ils le voient mais quand tu changes le rôle, le nouveau rôle n’est pas ping justement.
Donc ça sera comme Elliot a dit, il y en a qui se demanderont pourquoi ils n’ont pas eu la notification

**Comment by Serquand** [comment]
Sinon ce qu'on peut faire c'est juste un notif pour le nouveau rôle en réponse au cours au pire et pour les anciens rôles bon bah c'est pas ultra grave en vrai les erreurs ça arrivent quoi et j'ai moi-même toutes les options de notification et plus de 100 serveurs mais franchement c'est OK quoi juste un ping

**Comment by gtedavid** [comment]
Tough decision
Je sais pas ce qui a de mieux 😅 

C'est possible de la mettre en test : où, ça met le nom du rôle pingé par erreur en toute lettre + excuse, et ping le bon rôle en édition, et ping de ce rôle qui est supprimé ou pointe vers lien du cours ?

Et si ça le fait pas on laisse tomber ce test ?

**Comment by gtedavid** [comment]
Elliot, si tu peux rajouter Marc et Ylan sur le dépôt pls 😅

**Comment by lauragossip** [comment]
J’ai pas grand chose à rajouter par rapport à ce que j’avais a dire 
En soit en changeant le Ping les nouvelles personnes qui seront Ping ne le seront pas 
Donc on peut soit faire le msg nous meme en taguant le bon rôle soit on le fait avec le bot mais ca change rien

**Comment by gtedavid** [comment]
> J’ai pas grand chose à rajouter par rapport à ce que j’avais a dire En soit en changeant le Ping les nouvelles personnes qui seront Ping ne le seront pas Donc on peut soit faire le msg nous meme en taguant le bon rôle soit on le fait avec le bot mais ca change rien

Ok, you're the boss je ferme l'issue
