### ISSUE TITLE
Décision(s) à prendre vis à vis des nouvelles fonctionnalités AutoMod

### ISSUE THREAD

**Issue by gtedavid** [horizon-efrei/HorizonBot#64]
AutoMod pour le moment utilisé pour link/inv spam
Peut activer les mots interdits - pb : listes non gérées - serait à activer/implémenter si en prenant celles de Carl si on abandonne Carl

-----------
- double msg, supprimer
- enable/disable commands
- attachementspam
- censor

**Comment by gtedavid** [comment]
FONCTIONS modérateurs (au-dessus aussi)
- slowmode
- ban/softban/tempban/unban
- warn/removewarn/clearwarns/warns
- notes/clearnotes/clearnote/setnote/removenote (seulement possible pour mods, ou restreint à X rôle(s))
- kick
- lockdown/unlockdown channel
- hardmute/mute/unmute
- purge https://github.com/horizon-efrei/HorizonBot/issues/44
- reason (warn et autres je crois)

- newusers/oldusers/youngest
- oldest
- report/reportchannel (? pas sûr utile vu log ?)

- setnick (à tester pour voir les limitations au niveau des users, sur d'autres users etc)
- 
cleanup ? 
![image](https://user-images.githubusercontent.com/60758334/178930970-7b40e9f6-1b7f-403e-9c39-cb7e12597e60.png)

**Comment by noftaly** [comment]
- le cleanup pourra se faire avec la commande de purge `!purge --bot` (cf l'issue, qui décrit les options possibles)
- le newusers/oldusers/youngest/oldest peut se faire avec la commande de dump `!dump -o=joined -l=20` (= 20 premiers users) / `!dump -o=joined -l=20 -d` (= 20 derniers users)
- Pas sûr de l'utilité du report/reportchannel ? je n'ai pas compris, et sinon on peut toujours ping la modération
- Pas sûr de l'utilité du setnick ? Tout le monde a déjà la perm de changer son propre pseudo, et les modos peuvent changer ceux des autres

**Comment by gtedavid** [comment]
> * Pas sûr de l'utilité du setnick ? Tout le monde a déjà la perm de changer son propre pseudo, et les modos peuvent changer ceux des autres

le faire sur clavier uniquement 😅

Mais on peut le mettre en low prio, voire pas besoin implémenter

**Comment by gtedavid** [comment]
> * le cleanup pourra se faire avec la commande de purge `!purge --bot` (cf l'issue, qui décrit les options possibles)
> * le newusers/oldusers/youngest/oldest peut se faire avec la commande de dump `!dump -o=joined -l=20` (= 20 premiers users) / `!dump -o=joined -l=20 -d` (= 20 derniers users)

C'est implémenté ? ou tu proposes ? 😅

**Comment by noftaly** [comment]
> C'est implémenté ? ou tu proposes ? 😅

Le `!purge --bot` ce sera fait avec la commande de purge (pas encore dispo)
Le dump est déjà disponible

**Comment by gtedavid** [comment]
> AutoMod pour le moment utilisé pour link/inv spam Peut activer les mots interdits - pb : listes non gérées - serait à activer/implémenter si en prenant celles de Carl si on abandonne Carl
> 
> * double msg, supprimer
> * enable/disable commands
> * attachementspam [lié à issue, car type de channels](https://github.com/horizon-efrei/HorizonBot/issues/58)
> * censor

**Comment by noftaly** [comment]
@gtedavid Avec tous les messages ici ca devient compliqué de savoir ce qui est a faire, ce qui a été décidé etc.

Tu peux mettre à jour le message originel du post, avec toutes les choses que tu souhaiterais et rien d'autre please ? en enlevant les choses que l'on a éliminées.

J'ai "plié" tous les autres messages.

**Comment by gtedavid** [comment]
Closed, regrouped to #68
