### ISSUE TITLE
Retirer l'emoji d'une personne sur un menu rr

### ISSUE THREAD

**Issue by gtedavid** [horizon-efrei/HorizonBot#65]
Retirer une réaction d'une (ou plusieurs personnes ?) sur un menu rr

Reason : Pb avec bot au niveau des rr, personne ayant quitté le discord, personne voulant reset ses rôles

Priority low-medium

**Comment by lauragossip** [comment]
Je vois pas trop le problème et l’intérêt ici désolé 😅

**Comment by gtedavid** [comment]
> Je vois pas trop le problème et l’intérêt ici désolé 😅

Au lieu de gaspiller du temps à chercher une réaction sur un menu à 100 ou + réactions sur une emoji, une commande pour l'enlever

Parce que si tu enlèves le rôle à la personne ça n'enlève pas la réaction sur le menu, si elle y est

**Comment by lauragossip** [comment]
Ahhh en effet c’est intéressant ça

**Comment by noftaly** [comment]
Avec l'arrivée de l'onboarding nous n'avons plus aucun reaction-role, donc je ne vais pas ajouter de nouvelles features surtout si ca complique encore plus le système
