### ISSUE TITLE
Pouvoir créer des évènements (mix des reaction-roles/rappels)

### ISSUE THREAD

**Issue by gtedavid** [horizon-efrei/HorizonBot#67]
Pouvoir créer des évènements. Ca enverrai un message, on peut s'inscrire avec des réactions, et ca nous envoie des mps/pings de rappels

Contraintes : pas forcément des cours, réservés à 1 année même si ça peut concerner "principalement" une des années

**Comment by noftaly** [comment]
quid des évènements Discord built-in ?

**Comment by gtedavid** [comment]
> quid des évènements Discord built-in ?

Pas sûr de comprendre ta question précisément...

Tu parles de les lier ?

**Comment by noftaly** [comment]
non, pourquoi juste ne pas les utiliser directement ? il y a des rappels, tu peux t'inscrire, et c'est built-in dans l'application donc c'est plus sympa et plus intuitif

**Comment by gtedavid** [comment]
pour ping le rôle 😅 mais ok, je testerai voir
