### ISSUE TITLE
Date format création refus

### ISSUE THREAD

**Issue by gtedavid** [horizon-efrei/HorizonBot#75]
PRIORITY HIGH

**Décrivez le bug**

Date et heure saisies considérées comme invalide alor que pas encore passées

**Pour reproduire**

1. Créer un nv cours
2. Saisir normalement 
3. Saisir "27/07 06:09" (autour de 2am)
REFUS

**Comportement attendu**

Acceptation de la date et horaire

**Screenshots**

**Comment by gtedavid** [comment]
La saisie de la date et heure bloqué la création du cours, impossible de faire plus de 2 ou 3 essais puis refus total de prendre la proposition

**Comment by noftaly** [comment]
Tout fonctionne normalement (exemple avec le bot en production ci-dessous)

Je pense que c'est car tu mets des guillemets ?

https://user-images.githubusercontent.com/34779161/181227049-dcc41580-bed5-4634-8992-84fc30127467.mp4

**Comment by gtedavid** [comment]
Mb

**Comment by gtedavid** [comment]
Je crois que c'est parce que je le fais pour les rappels @noftaly

**Comment by noftaly** [comment]
yep mais les rappels il y a deux arguments `.remindme date message`, donc si tu veux mettre un espace dans la date tu es obligé de mettre des guillemets, pour que ce qu'il y a après l'espace soit interprété comme étant toujours dans la date, et n'étant pas le message.
Ici ce n'est pas nécessaire car on demande que la date 😄
