### ISSUE TITLE
Expliquer en DM les raisons de refus sur un menu de réaction-rôle

### ISSUE THREAD

**Issue by gtedavid** [horizon-efrei/HorizonBot#77]
Permettre aux utilisateurs de changer de rôles en dm pu de leur indiquer ce qui ne va pas (blocage)

**Comment by noftaly** [comment]
Pas sûr de comprendre.
Détail plus le problème actuel, la solution que tu proposes, et ce que le bot devrait faire exactement stp.

**Comment by gtedavid** [comment]
Si un utilisateur arrive pas à prendre un rôle sur un menu réaction, le bot lui inique pourquoi et le lien vers le menu pour prendre le rôle
ou le bot lui permet de choisir le rôle qu'il lui manque via dm (mais cette deuxième partie, est fait peu-être trop)

**Comment by lauragossip** [comment]
Oui en vrai pourquoi pas mais à voir si c’est pas trop galère à mettre en place

**Comment by noftaly** [comment]
Avec l'arrivée de l'onboarding nous n'avons plus aucun reaction-role, donc je ne vais pas ajouter de nouvelles features surtout si ca complique encore plus le système
