### ISSUE TITLE
Permettre d'avoir une icône/image sur les rr

### ISSUE THREAD

**Issue by gtedavid** [horizon-efrei/HorizonBot#78]
Permettre d'avoir une icône/image sur les rr
(modification, création ou suppression de la présence de l'image dans la rr)

**Comment by lauragossip** [comment]
En vrai je ne vois pas trop l’intérêt mais why not

**Comment by gtedavid** [comment]
> En vrai je ne vois pas trop l’intérêt mais why not

true, c'est plus esthétique
Mais comme indiqué dans la liste de prio, une fois l'Onboarding largely released, ça risque de sauter...
