### ISSUE TITLE
Message programmé via cmd pour posté un message

### ISSUE THREAD

**Issue by gtedavid** [horizon-efrei/HorizonBot#80]
Pouvoir programmer le poste d'un message via commande pour poster à une temps spécifique

**Comment by noftaly** [comment]
Détail plus le problème avec la solution que tu proposes et ce que le bot devrait faire exactement (exemple de commande etc etc)

**Comment by gtedavid** [comment]
En gros, le but serait de pouvoir poster l'annonce sur github une fois prête à une heure déterminée si personne ayant les perms peut la poster, ça serait de la poster via une commande tapée sur discord

en gros le bot ferait la manip de l'action workflow à une heure XX:XX, mais je suis en train de me rendre compte que ça peut être un poil plus compliqué que je croyais 😅

**Comment by noftaly** [comment]
Je ferme car on en a jamais eu besoin, et le travail que ca demanderai pour le faire n'en vaut pas la peine (on utilise déjà peu les webhooks...)
