### ISSUE TITLE
Personnaliser le message de changement de rôle en dm

### ISSUE THREAD

**Issue by gtedavid** [horizon-efrei/HorizonBot#81]
Les alternatives (rôles promo vs rôles cours)

**Comment by lauragossip** [comment]
Je n’ai pas compris l’intérêt

**Comment by noftaly** [comment]
Je n'ai pas compris non plus, d'autant plus que le bot n'envoie pas de message en MP quand on choisit un rôle

**Comment by gtedavid** [comment]
c'est pour notifier que l'utilisateur a changé de rôle, ça peut être toggle on ou off
mais elle n'est pas prioritaire - voire à abandonner parce que les utilisateurs peuvent trouver ça chiant

**Comment by lauragossip** [comment]
Oui surtout si ils sont dm 
En soit ça sert à rien de lui dire qu’il a changé de rôle en dm car soit c’est de sa propre volonté soit il le fait pas
