### ISSUE TITLE
Désactiver le ping ghost pour le ping du bot - !! trigger le bot si c'est le début d'un message de warning

### ISSUE THREAD

**Issue by gtedavid** [horizon-efrei/HorizonBot#84]
**Décrivez le bug**

auto delete les messages informatn HorizonBot qu'il a été ghost ping ou ne pas les afficher du tout

**Pour reproduire**

1. tapper !! et le reste du message
2. le bot envoie son msg automatique par rapport à l'utilisation des slash commands
3. puis on supprime le msg et le ghost ping est enclenché sauf que le bot n'est pas entrainé à réagir sur les messages où il est ghost ping

**Comportement attendu**

Pas de ghost ping msg attendu ou pas de trigger de !! s'il comporte un espace après ?

**Screenshots**

**Comment by gtedavid** [comment]
- [ ]  !! trigger le bot si c'est le début d'un message de warning
- [ ] Désactiver le ping ghost pour le ping du bot

**Comment by gtedavid** [comment]
> * [x]   !! trigger le bot si c'est le début d'un message de warning
> * [ ]  Désactiver le ping ghost pour le ping du bot

!! trigger has been turned off

**Comment by noftaly** [comment]
> Désactiver le ping ghost pour le ping du bot

Pas sûr d'avoir compris ? Si tu mentionnes le bot et supprime le message aucun message de ghost ping n'est envoyé, ca a été comme ca depuis le tout début 😄

**Comment by gtedavid** [comment]
Je retrouve pas....
Si jamais ça se reproduit, je rouvrirai l'issue. 😅

**Comment by gtedavid** [comment]
To be reopened if issue arises again.

**Comment by gtedavid** [comment]
Problem found 
when taging role + more than 1 role/person

In progress of being fixed by Noftaly
