### ISSUE TITLE
Accueillir les nouveaux membres

### ISSUE THREAD

**Issue by noftaly** [horizon-efrei/HorizonBot#9]
Envoyer un MP aux nouveaux membres en leur souhaitant bienvenue + leur assigner un modérateur "référent" qui recevra aussi un MP leur disant d'accueillir le nouveau membre etc.
Possibilité d'exclure/inclure des modérateurs/membres de la liste des "accueilleurs".
Les "accueilleurs" doivent tourner, pour que ce soit équitable.

Il faudrait que ce soit prêt avant la rentrée 2021, pour accueillir les nouveaux L1

**Comment by gtedavid** [comment]
Messages discord pour le msg de Carl : https://discord.com/channels/694220883815956580/825862547562299392/998550169312305152
