### ISSUE TITLE
Le bot ne prend pas en compte les changements fait sur la notification de cours

### ISSUE THREAD

**Issue by gtedavid** [horizon-efrei/HorizonBot#90]
**Décrivez le bug**

Changement des informations sur la notification de cours

**Pour reproduire**

1. Créer un cours
2. Le modifier via command (la notif)
3. les anciens canaux seront utilisés à la place des nouveaux

(Aucun changement dans la bdd ?)

**Comportement attendu**

Ping de rappel dans le canal qui a été changé dans le cours + affichage du bon vocal

**Screenshots**

[(voir ping)](https://discord.com/channels/694220883815956580/819374104108728340/1055526695953760377)

**Comment by noftaly** [comment]
Ce n'était pas un bug, les canaux n'ont jamais été changés (car ce n'est pas possible de les changer)
