### ISSUE TITLE
Possibilité de tag les gens d'un cours finis 

### ISSUE THREAD

**Issue by gtedavid** [horizon-efrei/HorizonBot#91]
Lorsque qu'un cours est terminé, le rôle se supprime

l'idée serait de permettre de tag les gens s'étant inscrit au cours de pouvoir être tag par un eprof.
on pourrait reprendre le principe de /dump mais sans passer à la ligne

Pb : -> si les eprofs utilisent dump, ils auraient accès à toutes les options de la commande........
Ce qui n'est pas le but.....

**Comment by noftaly** [comment]
Je vais faire que le rôle se renomme en terminé:
```diff
- Cours SP301: Révisions rattrapage (12/02 à 10:00)
+ [Terminé le 12/02] Cours SP301: Révisions rattrapage
```

et qu'il s'auto-supprimé au bout d'une semaine après la fin du cours 👍

**Comment by gtedavid** [comment]
Thanks 😅 
J'avais zappé que j'avais créé cette issue

**Comment by gtedavid** [comment]
👍🙏Thx
