### ISSUE TITLE
Purge - log messages supprimés (contenu et images)

### ISSUE THREAD

**Issue by gtedavid** [horizon-efrei/HorizonBot#94]
Purge - log messages supprimés (contenu et images) 
lorsque Purge est exécuté, cela log les msg supprimés

**Comment by lauragossip** [comment]
En vrai why not mais on a deja ca avec horizon bot non ?

**Comment by gtedavid** [comment]
> En vrai why not mais on a deja ca avec horizon bot non ?

on a la commande purge sur Horizon Bot

mais le souci, c'est que ça ne log pas les msg supprimés
Carl-bot le fait

tu vois la nuance ?

**Comment by noftaly** [comment]
Fixed by fc6afc0ef013e69ee8c096cacead9139a058ecac

**Comment by gtedavid** [comment]
👌 Nickel Elliot

**Comment by gtedavid** [comment]
@noftaly elle est en prod ? je le vois pas dans les logs 😅

**Comment by gtedavid** [comment]
@noftaly ?
j'ai une deuxième question, je viens de faire un /purge avec pour argument 5 (sans mettre rien, ça a tout purge 😅 )
Tu par du principe que si tu ne mets pas d'arg, c'est purge all ?

Je serais plus à l'aise si on met un --all pour tout
plus safe

**Comment by noftaly** [comment]
Ouvre une nouvelle issue, celle là est en rapport avec les logs.
Dans ta nouvelle issue pense a envoyer la commande complète car je n'ai pas compris la commande que t'as executée

**Comment by gtedavid** [comment]
> Ouvre une nouvelle issue, celle là est en rapport avec les logs. Dans ta nouvelle issue pense a envoyer la commande complète car je n'ai pas compris la commande que t'as executée

Ok noté, mb

**Comment by gtedavid** [comment]
https://github.com/horizon-efrei/HorizonBot/issues/96#issuecomment-1465310276 (les messages purgés ne s'affichent pas dans les logs)

Carl ✔️ 
HorizonBot ❌

**Comment by noftaly** [comment]
C'est résolu, mais pas en prod, il n'y a pas eu de release depuis le commit.

**Comment by gtedavid** [comment]
> C'est résolu, mais pas en prod, il n'y a pas eu de release depuis le commit. 

Ah 
Mb alors
