### ISSUE TITLE
Log |  Exécuteur ne s'affiche pas pour

### ISSUE THREAD

**Issue by gtedavid** [horizon-efrei/HorizonBot#95]
**Décrivez le bug**

La modification d'un salon et :octagonal_sign: Rôle enlevé dans les logs ne capture pas l'exécuteur.
Le bot affiche "undefined"
**Pour reproduire**

1. Étape 1 - Logs
2. Étape 2 - Modifier un canal pour tester
3. Étape 3 - Enlever un rôle d'un membre
4. Étape 4 - Regarder les logs affichés

**Comportement attendu**

Le bot mention la personne ayant faite ces modifications
**Screenshots**

**Comment by noftaly** [comment]
Je ne peux pas reproduire (même en production sur Ef'Réussite) :

<img width="241" alt="image" src="https://user-images.githubusercontent.com/34779161/222959782-85c8b70c-cd43-41c4-b37e-e8c671ba9880.png">

Je laisse ouvert encore qques jours si jamais le problème réapparaît

**Comment by gtedavid** [comment]
> Je ne peux pas reproduire (même en production sur Ef'Réussite) :
> 
> <img width="241" alt="image" src="https://user-images.githubusercontent.com/34779161/222959782-85c8b70c-cd43-41c4-b37e-e8c671ba9880.png">
> 
> Je laisse ouvert encore qques jours si jamais le problème réapparaît

https://discord.com/channels/694220883815956580/888452710091853905/1081930443143790622

**Comment by gtedavid** [comment]
(Discord n'affiche pas clairement qui supprime certains éléments)
