### ISSUE TITLE
Mettre l'argument "nombre" obligatoire pour la commande purge

### ISSUE THREAD

**Issue by gtedavid** [horizon-efrei/HorizonBot#96]
**Décrivez le bug**

Lorsqu'on exécute la commande /purge 5 (sans prendre d'interaction), le bot purge tous les messages du canal/fil.

**Pour reproduire**

1. Créer un fil
2. Taper des messages random
3. Tagger le bot
4. /purge 4
5. le bot supprimera tout

**Comportement attendu**

Le mieux c'est de bloquer la suppression de "tout" dans le canal à un `--all` pour éviter de supprimer par accident et si un argument non prévu est saisi, ne supprimer que le dernier message....

N.B. les messages supprimés par /purge ne semble logé que par Carl-Bot
**Screenshots**

**Comment by noftaly** [comment]
Ce n'est pas comme ca que fonctionne une slash commande, pour donner des arguments il **faut** utiliser les options.
Autrement dit, il faut mettre le `5` dans l'option `nombre`:
<img width="307" alt="image" src="https://user-images.githubusercontent.com/34779161/224543996-f45f40fc-4b5a-44df-9f1d-dca283775fe0.png">

Ne pas utiliser l'option, comme ceci
<img width="231" alt="image" src="https://user-images.githubusercontent.com/34779161/224544011-b8b4115b-fbb2-403d-a425-ac99a58bb3a6.png">
Fera qu'aucun argument n'est reconnu.

Ce n'est donc pas un bug.

En revanche, je peux mettre l'argument `nombre` en obligatoire pour être forcé de le spécifier.

**Comment by gtedavid** [comment]
> > N.B. les messages supprimés par /purge ne semble logé que par Carl-Bot
> 
> Suivit par #94 (résolu)

Justement, j'ai pas l'impression que ça fonctionne

**Comment by gtedavid** [comment]
Je viens de le refaire #94 n'est pas résolu
